### PR TITLE
NiFi 1.26.0 update

### PR DESCRIPTION
**Pull request by michaelarnauts**
* Update the swagger definitions to 1.26.0 and re-ran the code generation

### CODE REVIEW

**Comment by michaelarnauts** [comment]
I've tried to run the tests, but it seems they don't work on Python 3.12:

```
ImportError while importing test module '/home/michael/Development/nipyapi/tests/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_utils.py:12: in <module>
    from deepdiff import DeepDiff
venv/lib/python3.12/site-packages/deepdiff/__init__.py:7: in <module>
    from .diff import DeepDiff
venv/lib/python3.12/site-packages/deepdiff/diff.py:19: in <module>
    from collections import Mapping
E   ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.12/collections/__init__.py)
```

Also, I couldn't install all dev requirements since `watchdog` has to be an old version to support python 2.

I wonder if it's time to drop the Python 2 compatibility?

**Comment by Chaffelson** [comment]
Superceded by https://github.com/Chaffelson/nipyapi/pull/365
